---
version: '2'
catalog:
  name: Kartoza Resilio
  description: "Resilio sync all set up and ready to go in Rancher."
  version: 0
  uuid: kartoza-btsync-0
  questions:
  - variable: BTSYNC_SECRET
    label: "secret"
    description: "Resilio sync read/write key for syncing files"
    required: true
    default: 
    type: "string"
  - variable: BTSYNC_DEVICE
    label: "device"
    description: "Resilio sync device name"
    required: true
    default: 
    type: "string"
  - variable: BTSYNC_VOL
    label: "volume_path"
    description: "enter a volume name (like 'resilio-data') and a docker volume will be used, else enter a host path and a bind mount will be used"
    required: true
    default: 
    type: "string"
  - variable: "HOST_AFFINITY"
    label: "Label of host to deploy on"
    description: |
      To keep containers running on specific
      hosts, provide label attached to host
      to deploy on. For example, if you create a label 
      when deploying your host with key gis-box-id
      and value 3 then you would enter here gis-box-id=3
    required: true
    type: string
    default:
  services:
    btsync-data:
      scale: 1
      labels:
        io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}