# Base docker-compose file for rancher in staging environment
# This file has some specific tweaks for staging environment
# You can copy this file and paste it when creating a new stack in rancher
# It will try to sync related files

# Rancher currently only supports up to version 2
# If you want to use docker-swarm, create another orchestration with version 3
version: '2'
volumes:
  activity-logs:

services:

  db:
    image: kartoza/postgis:9.4-2.1
    hostname: db
    environment:
     - USERNAME=docker
     - PASS=docker
    labels:
      io.rancher.container.pull_image: always
    restart: unless-stopped

  web:
    image: kartoza/osm-reporter:latest
    hostname: web
    environment:
      - PGUSER=docker
      - PGPASSWORD=docker
      - PGHOST=db
    depends_on:
      - db
    ports:
      - "8080:8080"
    expose:
      - 8080:8080/tcp
    links:
      - db:db
    volumes:
      - activity-logs:/logs:rw
    labels:
      io.rancher.container.pull_image: always
      # Each web instance gets it's own db instance
      io.rancher.sidekicks: db
    restart: unless-stopped

  # Web load balancer
  web-lb:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
      - "80:80"
    expose:
      - 80:80/tcp
    links:
      - web:web
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
    restart: unless-stopped

  btsync-logs:
    # BTSync backups for activity logs
    image: kartoza/btsync
    hostname: btsync-media
    restart: unless-stopped
    volumes:
      - activity-logs:/logs:rw
    environment:
      - SECRET=${BTSYNC_MEDIA_SECRET}
      - DEVICE=ProjectaMedia

