version: '2'
catalog:
  name: "GIS Quick"
  description: "Gisquick is an open source geospatial data publishing platform by Marcel Dancák, Martin Landa, Jáchym Čepický, Ivan Minčík and Rastislav Mičaník. Rancher orchestration by Kartoza. It was developed for rapid sharing of our projects created with QGIS. We put together minimal set of functions for useful generic web mapping application. We created it for ourselves as well as for you. Let’s use it and share our great GIS outputs with others easily and much quicker."
  version: 1
  uuid: gisquick-0
  questions:
    - variable: QGIS_BACKEND_INSTANCE_COUNT
      label: "Reporter backend instance count"
      description: "How many OSM reporter rendering instances to start with."
      required: true
      default: 1
      type: "int"
    - variable: BTSYNC_MEDIA_SECRET
      label: "Logs key"
      description: "Resilio sync read/write key for syncing geojson activity logs"
      required: false
      default:
      type: "string"
    - variable: CREW
      label: "Comma separated list of crew members"
      description: "Valid OSM users names of people actively working on your data gathering project. When set, an additional tag will be added in the user profile areas to indicate those who are crew members."
      required: false
      default: ''
      type: "string"
    - variable: BBOX
      label: "Initial BBOX for when page loads."
      description: "Default bbox to use for the map and the stats. Format is: {SW_lng},{SW_lat},{NE_lng},{NE_lat}."
      required: false
      default: '20.411482,-34.053726,20.467358,-34.009483'
      type: "string"
    - variable: CACHE_DIR
      label: "Directory to cache OSM files."
      description: "Path to a dir where to cache the OSM files used by the backend. Note you may need to clear this directory out periodically."
      required: false
      default: '/tmp'
      type: "string"
    - variable: LOG_DIR
      label: "Path to a dir where to store request logs in geojson format."
      description: "OSM-Reporter will log requests as geojson files - one file per request. The attributes of each geojson file will contain the following:

feature_type (building, roads etc.)
qgis_version
inasafe_version (if applicable)
year / month / day / hour of request
bounding box of request as a GeoJSON geometry

If you use the btsync log sync option, make sure to leave this at its default value."
      required: false
      default: '/logs'
      type: "string"
services:
  web-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: web-lb
        priority: 1
        # we are forwarding to port 8080 so we need to use tcp not http
        protocol: tcp
        service: qgisserver
        source_port: 9000
        target_port: 90
      health_check:
        healthy_threshold: 2
        response_timeout: 2000
        port: 42
        unhealthy_threshold: 3
        initializing_timeout: 60000
        interval: 2000
        reinitializing_timeout: 60000
  qgisserver:
    scale: ${QGIS_BACKEND_INSTANCE_COUNT}
    start_on_create: true
