version: '2'
catalog:
  name: "GIS Quick"
  description: "GISQUICK is an Open Source GeoSpatial data publishing platform by Marcel Dancák, Martin Landa, Jáchym Čepický, Ivan Minčík and Rastislav Mičaník. Rancher orchestration by Kartoza. It was developed for rapid sharing of our projects created with QGIS. We put together minimal set of functions for useful generic web mapping application. We created it for ourselves as well as for you. Let’s use it and share our great GIS outputs with others easily and much quicker."
  version: 1
  uuid: gisquick-0
  questions:
    - variable: QGIS_BACKEND_INSTANCE_COUNT
      label: "QGIS Server backend instance count"
      description: "How many QGIS Server rendering instances to start with."
      required: true
      default: 1
      type: "int"
