name: "Docker OSM"
description: "OSM PostGIS database with automatic updates from OSM periodically. Structure of Sync Directory
              should resemble https://github.com/kartoza/docker-osm/tree/develop/settings"
version: 1
category: Software
maintainer: Kartoza (Pty) Ltd. - Tim Sutton, tim@kartoza.com
license: GPL v3
projectURL: https://github.com/kartoza/docker-osm.git
