name: QGIS Backend
description: QGIS backend and resilio sync
version: 2.18
category: GIS
maintainer: Kartoza (Pty) Ltd. - Tim Sutton, tim@kartoza.com
license: GPL v3
projectURL: https://github.com/kartoza/docker-qgis-server
