version: '2'
catalog:
  name: Kartoza Geoserver
  version: v2.10.5
  questions:
  - variable: PG_HBA_RANGE
    label: PostgreSQL pg_hba address range from which connections should be allowed. See http://rancher.com/docs/rancher/latest/en/rancher-services/networking/#differences-from-previous-releases for the network range that Rancher uses.
    required: true
    default: 10.42.0.0/16
    type: string
  - variable: BTSYNC_DB_SECRET
    label: Resilio sync read/write key for syncing database backups
    required: true
    default: 
    type: string
  - variable: BTSYNC_MEDIA_SECRET
    label: Resilio sync read/write key for syncing Geoserver media backups
    required: true
    default: 
    type: string
