catalog:
  name: "FETI"
  description: "Helping South African youth find tertiary education opportunities"
  version: 1
  uuid: kartoza-feti-1
  questions:
    - variable: REPORTER_BACKEND_INSTANCE_COUNT
      label: "Backend instance count"
      description: "How many instances to start with."
      required: true
      default: 1
      type: "int"
    - variable: BTSYNC_MEDIA_SECRET
      label: "Logs key"
      description: "Resilio sync read/write key for syncing activity logs"
      required: false
      default:
      type: "string"
services:
  web-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: web-lb
        priority: 1
        # we are forwarding to port 8080 so we need to use tcp not http
        protocol: tcp
        service: web
        source_port: 80
        target_port: 8080
      health_check:
        healthy_threshold: 2
        response_timeout: 2000
        port: 42
        unhealthy_threshold: 3
        initializing_timeout: 60000
        interval: 2000
        reinitializing_timeout: 60000
  web:
    scale: ${BACKEND_INSTANCE_COUNT}
    start_on_create: true
  db:
    scale: ${BACKEND_INSTANCE_COUNT}
    start_on_create: true
