name: "PostGIS 11.0-2.5"
description: "PostGIS is a FOSS geospatial datastore for PostgreSQL."
version: 1
category: Software
maintainer: Kartoza (Pty) Ltd. - Tim Sutton, tim@kartoza.com
license: GPL v3
projectURL: https://github.com/kartoza/docker-postgis
