version: '2'
catalog:
  name: "Kartoza Geonode"
  description: "Kartoza's spin of GeoNode with a QGIS backend."
  version: 1
  uuid: kartoza-geonode-0
  questions:
    - variable: QGIS_BACKEND_INSTANCE_COUNT
      label: "QGIS backend instance count"
      description: "How many QGIS backend rendering instances to start with."
      required: true
      default: 4
      type: "int"
    - variable: BTSYNC_DB_SECRET
      label: "Database backups key"
      description: "Resilio sync read/write key for syncing database backups"
      required: true
      default: 
      type: "string"
    - variable: BTSYNC_MEDIA_SECRET
      label: "Media backups key"
      description: "Resilio sync read/write key for syncing geonode media backups"
      required: true
      default: 
      type: "string"
