name: GeoServer
description: GeoServer with PostGIS and backups via resilio sync
version: 1
category: GIS
maintainer: Kartoza (Pty) Ltd. - Tim Sutton, tim@kartoza.com
license: GPL v3
projectURL: https://github.com/kartoza/docker-geoserver
