.catalog:
  name: "Kartoza PostGIS 10.0-2.4 Deprecated in favour of generic PostGIS"
  description: "This is [PostGIS](http://postgis.org) 2.4 running on PostgreSQL 10.0 all set up and ready to go in Rancher."
  version: 10.0-2.4
  uuid: kartoza-postgis
  questions:
  - variable: POSTGRES_DUMP_PREFIX
    label: "Prefix to use in the name of database dumps made by the backup container."
    required: true
    default: "postgis"
    type: "string"
  - variable: POSTGRES_DB
    label: "PostgreSQL db to create."
    required: true
    default: gis
    type: "string"
  - variable: POSTGRES_USER
    label: "PostgreSQL superuser account to create."
    required: true
    default: docker
    type: "string"
  - variable: POSTGRES_PASS
    label: "PostgreSQL superuser password to create."
    required: true
    default: docker
    type: "string"
  - variable: POSTGRES_HBA_RANGE
    label: "Database allowed hosts"
    description: "PostgreSQL pg_hba (host based authentication) address range from which connections should be allowed. See http://rancher.com/docs/rancher/latest/en/rancher-services/networking/#differences-from-previous-releases for the network range that Rancher uses. NOTE That the default is to be open / public!"
    required: true
    default: 0.0.0.0/0
    type: "string"
  - variable: POSTGRES_PORT
    description: "Postgres port"
    label: "Port on which the database should be served. Typically 5432"
    required: true
    default: 5432
    type: "int"
  - variable: BTSYNC_DB_SECRET
    label: "Database backups key"
    description: "Resilio sync read/write key for syncing database backups"
    required: false
    default: ""
    type: "string"
  - variable: "HOST_AFFINITY"
    label: "Label of host to deploy on"
    description: |
      To keep containers running on specific
      hosts, provide label attached to host
      to deploy on. For example, if you create a label
      when deploying your host with key gis-box-id
      and value 3 then you would enter here gis-box-id=3
    required: true
    type: string
    default:
    services:
      db:
        scale: 1
        labels:
          io.rancher.scheduler.affinity:host_label: ${HOST_AFFINITY}