name: OSM Reporter 
description: A simple tool for getting stats for an openstreetmap area.
version: 1
category: GIS
maintainer: Kartoza (Pty) Ltd. - Tim Sutton, tim@kartoza.com
license: GPL v3
projectURL: https://github.com/kartoza/osm-reporter
