
.catalog:
  name: "Kartoza QGIS Server 2.18"
  description: "Kartoza's spin of a Dockerised QGIS backend."
  version: v2.18
  uuid: kartoza-qgis-server-0
  questions:
    - variable: QGIS_BACKEND_INSTANCE_COUNT
      label: "QGIS backend instance count"
      description: "How many QGIS backend rendering instances to start with."
      required: true
      default: 4
      type: "int"
    - variable: WEBSERVER_PORT
      description: "Website port"
      label: "Port on which the site should be served. Typically 80"
      required: true
      default: 80
      type: "int"
    - variable: QGIS_DEBUG_LEVEL
      label: "Debug level for QGIS Server"
      description: "Log level 0 is the lowest (catch all), 5 is the highest (only fatal error)"
      required: true
      default: 5
      type: "int"
    - variable: QGIS_PROJECT_FILE
      label: "Default project file for QGIS Server"
      description: "If you leave this blank you will need to explicitly include a project file in your OGC requests."
      required: false
      default: "/project/project.qgs"
      type: "string"
    - variable: BTSYNC_DATA_SECRET
      label: "Resilio sync key for QGIS projects and data."
      description: "Resilio sync read/write key for syncing GIS data. Use a read only key if you never want your data altered on the server side (which is probably the normal case unless you plan to use WFS-T."
      required: false
      default: 
      type: "string"
    - variable: BTSYNC_PLUGINS_SECRET
      Plugins label: "key"
      description: "Resilio sync read only key for syncing QGIS Server side plugins."
      required: false
      default: 
      type: "string"
    - variable: "HOST_AFFINITY"
      label: "Label of host to deploy on"
      description: |
        To keep containers running on specific
        hosts, provide label attached to host
        to deploy on. For example, if you create a label
        when deploying your host with key gis-box-id
        and value 3 then you would enter here gis-box-id=3
      required: true
      type: string
      default:
      services:
        qgis-server:
          scale: 1
          start_on_create: true
          lb_config:
            certs: []
            port_rules:
            - hostname: qgis-server
              priority: 1
              protocol: http
              service: qgis-server-backend
              source_port: 80
              target_port: 80
            health_check:
              healthy_threshold: 2
              response_timeout: 2000
              port: 42
              unhealthy_threshold: 3
              initializing_timeout: 60000
              interval: 2000
              reinitializing_timeout: 60000
        qgis-server-backend:
          scale: ${QGIS_BACKEND_INSTANCE_COUNT}
          start_on_create: true
