name: "Generic GeoNode"
description: |
    Generic GeoNode deployment - Kartoza Fork.
version: "v1"
category: "GIS"
maintainer: "Geo-Solutions.it (Kartoza fork)"
license: "GPL"
projectURL: "http://geonode.org"
